### ISSUE TITLE
怎么显示在屏幕上？

### ISSUE THREAD

**Issue by ShuiHuo** [RedL0tus/Activate-Plasma#1]
桌面添加小部件只能添加到桌面，打开应用程序就看不见了。怎么才能让它显示在所有应用程序上面？

**Comment by RedL0tus** [comment]
暂时没有办法，这目前只是个 Plasma 桌面控件没有办法做到保持最前。需要做成一个 KWin 插件或者窗口才有办法保持最前，但是我目前没有计划去做那些东西。
